### ISSUE TITLE
Any way to actually build the CLI binary when installing via NPM?

### ISSUE THREAD

**Issue by tobz** [jnovack/storm-extract#7]
I realize that this is primarily meant to function as a Node module, hence the Gyp binding, but it would be super swell if this could also build the CLI binary to go along with it.

I'm not sure if that's feasible, or if we'd have to write a JS wrapper script to load the NodeJS module.  Happy to help if you have a rough idea of what it would take, but this was more of a passing thought that I didn't want to lose track of... so I figured I'd make an issue out of it. :P

**Comment by jnovack** [comment]
I don't believe so.  CLI would qualify as a different build environment, and thus require different dependancies.  That's why there's specific Node headers and declarations.

Since you may not have the required OS dependancies, I don't know if I want to kick off a build that might fail.  

Ideas?

**Comment by tobz** [comment]
Yeah, that's totally fair.

I guess I'm mostly after a way to automate the cmake part, but yeah, I realize that is OS dependent and not fully unified in the way that Gyp is.

I'll do some more poking/research.  Maybe there's a way to fake out Gyp into "building" the actual commands it takes to build the binary?  With a flag or something?

It's not a huge deal... just trying to avoid extraneous individual steps. :)

**Comment by jnovack** [comment]
Gyp builds the binary only as a Node extension.  It'll only run if you have Node installed. It does not build a stand-alone "`storm-extract.exe`" (bad example) that you can copy from computer to computer. To do so, you need `cmake` to build the (non-Node) OS stand-alone executable.  

IS there a way to auto-build the stand-alone version as soon as you do an `npm install storm-extract`?  Yes.  It would require writing a (node) script to additionally check the machine for `cmake` and then run it, and silently fail if you don't have `cmake` or the `cmake` build fails (because the `npm install` has to return `0` or it won't be installed as a node-module).  **But** that's disingenuous because at this point, you are not sure that the `cmake` executable failed or worked from an installation point of view because your installed had to be "successful" to pass npm.

If you sort that out, it's pretty trivial to modify the `package.json` to run your custom script instead of `node-gyp rebuild`.

```
{
  "scripts": {
    "install": "node my-install-script.js"
    }
}
```

**Comment by jnovack** [comment]
Closing due to improbability of solution. Sorry. :(
